##########################################################
##################  所有profile共有的配置  #################
##########################################################

# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 10080
  servlet:
    context-path: /web
dynamicLoad:
  info: UappInterface1ImplOut1
  interface1impl: com.aiosp.uapp1.Impl4Interface1
#  Impl4Interface1

###################  imprint-web配置  ###################
platform:
  lang: asiainfo
  swagger-open: true #false #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  session-open: true #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
  file-upload-path: imgs/ #文件上传目录(不配置则为java.io.tmpdir目录)

  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  max-history-version: 5 #历史版本记录最大值

datajiang:
  enable-admin: false
  data-permission: /admin/data

###################  spring配置  ###################
spring:
  session:
    redis:
      flush-mode: on_save
      namespace: session.datajiang
      cleanup-cron: 0 * * * * *
    store-type: redis

    #redis:
    #enabled: false #如果没安装redis就为false
    #host: 10.1.253.50
    #port: 6379
    #password: datajiang
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  messages:
    basename: i18n/messages
    cache-second: 3600

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/datajiang/**/**/mapping/*.xml
  typeAliasesPackage: com.datajiang.common.persistence.model;com.datajiang.modular.code.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/microtools?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: dj
    password: 123456
    filters: log4j,wall,mergeStat
logging:
  #  level.root: error
  level.root: info
  level.com.datajiang: debug
  level.org.springframework: info
  #level.org.apache.ibatis: info
  #level.org.apache.ibatis: debug
  #level.org.apache.kafka: none
  file:
    path: logs/datajiang/
    file: datajiang.log

beetl:
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false
server:
  port: 7080
mybatis-plus:
  global-config:
    refresh-mapper: true
platform:
  share-open: false #是否开启分享,自己用可以关闭(true/false)
  gen-local: true #是否允许在本地生成代码

